### ISSUE TITLE
Gateway hangs intermittently

### ISSUE THREAD

**Issue by j4zzcat** [TheThingsProducts/gateway#22] opened 2018-03-22 11:38 UTC
Hi, 

My gateway stops working intermittently. When this happens, the leds indicate a wifi problem (led1:on, led2:flashing_fast, led3:on, led4:off, led5:off), and a power off/on is needed. Needless to say, my wifi network is stable as a rock. The problem usually occurs within an hour of operation, and had happened dozens of time since I initially installed the gateway, a few days ago.

With **the white lid open**, the problem had not manifested itself for 24 hours, after which I ended my test. I'm therefor speculating that the problem is somehow related to the ambient temperature inside the gateway enclosure. During the test, the gateway's temperature was about 40C - 44C.  

```
Hardware: v1
Bootloader: r1-7167873a (2017-06-02T13:48:18Z)
Firmware: v1.0.2-475aef56 (2018-03-15T09:43:08Z)
```

**Comment by j4zzcat** [comment] 2018-03-26 06:04
Script started on Mon Mar 26 08:50:36 2018
command: picocom /dev/cu.usbmodem144331 -b 115200
picocom v3.1

port is        : /dev/cu.usbmodem144331
flowcontrol    : none
baudrate is    : 115200
parity is      : none
databits are   : 8
stopbits are   : 1
escape is      : C-a
local echo is  : no
noinit is      : no
noreset is     : no
hangup is      : no
nolock is      : no
send_cmd is    : sz -vv
receive_cmd is : rz -vv -E
imap is        : 
omap is        : 
emap is        : crcrlf,delbs,
logfile is     : none
initstring     : none
exit_after is  : not set
exit is        : no

!! Settings mismatch !! Type [C-a] [C-v] to see actual port settings

Type [C-a] [C-h] to see available commands
Terminal ready
AltSoftSerial Test Begin
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Accepted packet
MQTT: Sending UPLINK OK
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 37
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Packet dropped! Bad CRC
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 38
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Accepted packet
MQTT: Sending UPLINK OK
LORA: Accepted packet
MQTT: Pending UPLINK OK
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQT\: Sending status succeeded: 39
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
SNTP: State change fro[º¢½1
SNTP: Statd change from 1 to 2
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
SNTP: State change from 2 to 3
SNTP: State change from 3 to 4
SNTP: State change from 4 to 5
SNTP: State change from 5 to 6
SNTP: State change from 6 to 7
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 40
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heausage: 262KB (263KB), free: 77KB
LORA: Kick LoRa module with ACK after not acked it for 60s
MON: SYS Stack size: 2847
LON: heap usage: 262KB (263KB), free: 77KB
LORA'
+ÁÑpacket
MQTT: Sending UPLINK OK
MQTT: Sending status packet
MQTT: Sending status succeeded: 41
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 42
MON: SYS Stack size: 2847
LON: heap usage: 262KB 263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Kick LoRa module with ACK after not acked it for 60s
MQTT: Sending status packet
MQTT: Sending status succeede¢j
LORA: Accdpted packet
MQTT: Sending UPLINK OK
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 44
MON: SYS Stack siza: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: he`p usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Packet dropped! Bad CRC
MQTT: Sending status packet
MQTT: Sending status succeeded: 45
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Accepted packet
MQTT: Sending UPLINK OK
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
LORA: Packet dropped! Bad CRC
MQTT: Seding status succeeded: 46
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77{B
MON: SYS Stack size: 2847
MON: heap usage: 26>KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 47
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Accepted 
­Ñ5
MQTT: Sending UPLINK OK
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 48
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 49
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Packet dropped! Bad CRC
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77CB
MQTT: Sending status packet
MQTT: Sending status succeeded: 50
LORA: Accepted packet
MQTT: Sending UPLINK OK
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 51
LORA: Packet dropped! Bad CRC
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Packet dropped! Bad CRC
LORA: Accepted packet
MQTT: Sending UPLINK OK
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT Sending status packet
MQTT: Sending status su`ceeded: 52
MON: SYS Stack size: 2847
MON: hdap usage: 262KB (263KB), free: 77KB
LORA: Accepted packet
MQTT: Sending UPLINK OK
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 53
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending status packet
MQTT: Sending status succeeded: 54
MON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
LORA: Kick LoRa module with ACK after not acked it for 60s
LORA: Accepted packet
FAILMON: SYS Stack size: 2847
MON: heap usage: 262KB (263KB), free: 77KB
MQTT: Sending UPLINK failed: -1

MAIN: MQTT error

MAIN: Leaving state 5
MAIN: Entering state 6
INET: State change to 0
WIFI: Disabling modules
SNTP: State change from 7 to 8
CB: Disconnect
Head magic match void: trying to free an already freed block, ignore
SNTP: State change from 8 to 1
WIFI: Entering state 3
WIFI: Enabling modules for client
WIFI: Entering state 6
WIFI: IP Address: 0.0î0.0 
CB: INET: Gateway has WiFi
INET: State change to 2
INET: Connected to a etwork, waiting for DHCP lease, checking validity with ping
SNTP: State change from 1 to 2
WIFI: IP Address: 192.168.0.60 
INET: State change to 3
INET: Ping probe
INET: Error sending probe on Eth
SNTP: State change from 2 to 6
MON: SYS Stack size: 2847
MON: heap usage: 168KB (263KB), free: 171KB
INET: Ping Timeout
INET: Ping probe
INET: Error sending probe on Eth
LORA: Packet dropped! Bad CRC
INET: Ping Timeout
INET: Ping probe
INET: Error sending probe on Eth
MON: SYS Stack siz}: 2847
MON: heap usage: 168KB (263KB), free: 171KB
INET: Ping Timeout
INET: State change to 1
WIFI: Disabling modules
CB: Disconnect
Head magic match void: trying to free an already freed block, ignore
SNTP: State change from 6 to 1
WIFI: Entering state 3
WIFI: Entering state 4
WIFI: Entering SCAN state 1
Scan is completed successfully
WIFI: Entering SCAN state 2
WIFI: Entering SCAN state 3
Head magic match void: trying to free an already freed block, ignore
SNTP: State change from 1 to 1
WIFI: Entering SCAN state 4
WIFI: Entering SCAN state 5
WIFI: Entering SCAN state 0
WIFI: Entering state 5
WIFI: Enabling modules for server
WIFI: Entering state 6
GIFI: IP Address: 192.168.84.1 
CB: MON: SYS Stack size: 2847
MON: heap usage: 167KB (263KB), free: 171KB
LORA: Packet dropped! Bad CRC
MON: SYS Stack size: 2847
MON: heap usage: 167KB (263KB), free: 171KB
MON: SYS Stack size: 2847
MON: heap usage: 167KB (263KB), free: 171KB
LORA: Accepted packet
MON: SYS Stack size: 2847
OON: heap us`ge: 167KB (263KB), free: 171KB
LORA: Accepted packet
MON: SYS Stack size: 2847
MON: heap usage: 167KB (263KB), free: 171KB
OON: SYS Stack size: 2847
MON: heap usage: 167KB (263KB), free: 171KB
MON: SYS Stack size: 2847
MON: heap usage: 167KB (263KB), free: 171KB
MON: SYS Stack siza: 2847
MOÎ: heap usage: 167KB (263KB), free: 071KB

Terminating...
Thanks for using picocom

Script done on Mon Mar 26 09:01:36 2018

**Comment by htdvisser** [comment] 2018-03-26 07:39
Duplicate of #21 (except that in this case the gateway didn't reboot)

**Closed by htdvisser** 2018-03-26 07:39 UTC
Labels: bug, c/mqtt, duplicate

**Comment by j4zzcat** [comment] 2018-03-26 16:30
After additional testing, there’s no evidence that the problem relates to the ambient temperature within the gateway enclosure.
